apiVersion: v1
kind: Pod
metadata:
  labels:
    name: cart
    role: backend
  name: cart
spec:
  containers:
    - name: cart
      image: zutherb/cart-service
      ports:
        - containerPort: 18100