apiVersion: v1
kind: Pod
metadata:
  labels:
    name: catalog
    role: backend
  name: catalog
spec:
  containers:
    - name: catalog
      image: zutherb/catalog-frontend
      ports:
        - containerPort: 80
          hostPort: 80
      env:
        - name: CHECKOUT_DESIGN
          value: "standard"