apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mongodb
    role: database
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: "27017"
          hostPort: "27017"
        - containerPort: "28017"
          hostPort: "28017"
      command:
        - "mongod"
        - "--smallfiles"