apiVersion: v1
kind: Pod
metadata:
  labels:
    name: product
    role: backend
  name: product
spec:
  containers:
    - name: product
      image: zutherb/product-service
      ports:
        - containerPort: 18080