apiVersion: v1
kind: Pod
metadata:
  labels:
    name: shop
    role: frontend
  name: shop
spec:
  containers:
    - name: shop
      image: zutherb/monolithic-shop
      ports:
        - containerPort: 8080